name: hello-world
on: push
jobs:
  my-job:
    runs-on:
      container: gradle:6-jdk11
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Clone-down
        uses: actions/checkout@v3