name: hello-world
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Test
        run: ci/unit-test-app.sh
      - name: Set file permissions
        run: chmod +x ci/build-app.sh
      - name: Build app
        run: ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  job-2:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Test
        run: ci/unit-test-app.sh
      - name: Set file permissions
        run: chmod +x ci/build-app.sh
  job-3:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Test
        run: ci/unit-test-app.sh
      - name: Set file permissions
        run: chmod +x ci/build-app.sh
  job-4:
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
      - job-3
    steps:
      - name: JOB 4
        run: echo "I am done waiting"
